apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: echoderder
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/vibhanshu-thakur-dev/echoderder.git