apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.konghq.com 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: kong
  interval: 1m
  releaseName: kong
  targetNamespace: kong