
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: echoserver
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/vibhanshu-thakur-dev/echoserver.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echoserver
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./templates/echoserver
  prune: true
  sourceRef:
    kind: GitRepository
    name: echoserver
