apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echoberber
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./templates/echoserver
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild: 
    substitute:
      instance_name: "default"
