apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echoberber
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./templates/echoberber
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
