apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echoserver
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./templates/echoserver
  prune: true
  sourceRef:
    kind: GitRepository
    name: lux-system
