apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./templates/kong_helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system


