apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-proxy
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
  - host: api.sort-tree.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kong-kong-proxy
            port:
              number: 80