apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kong
  namespace: flux-system
resources:
  - release.yaml
  - repository.yaml
  - namespace.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease