apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress
      sourceRef:
        kind: HelmRepository
        name: kong
  interval: 1m
  releaseName: kong
  targetNamespace: kong
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    proxy:
      annotations:
        "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
        "service.beta.kubernetes.io/aws-load-balancer-internal": "false"        