apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ping-server
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./templates/ping-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
