apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${instance_name:=echoserver}"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: "${instance_name:=echoserver}"
  template:
    metadata:
      labels:
        app: "${instance_name:=echoserver}"
    spec:
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: "${instance_name:=echoserver}"
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
