apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "${instance_name:=echoserver}"
  annotations: 
    "cert-manager.io/cluster-issuer": "letsencrypt-cert-issuer"
spec:
  ingressClassName: kong
  rules:
  - host: kong.eks.vt.dev.quaddemo.co.uk
    http:
      paths:
      - path: "/${instance_name:=echoserver}"
        pathType: Prefix
        backend:
          service:
            name: "${instance_name:=echoserver}"
            port:
              number: 80
  tls:
    - hosts:
      - kong.eks.vt.dev.quaddemo.co.uk
      secretName: kong.eks.vt.dev.quaddemo.co.uk-certificate-secret
