apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- overlay/echoserver/repository.yaml
- overlay/echoderder/repository.yaml
- overlay/echoberber/repository.yaml
- overlay/echoserver/echoserver.yaml
- overlay/echoderder/echoderder.yaml
- overlay/echoberber/echoberber.yaml
- overlay/kong_helm